#
# Copyright (c) 2018, NVIDIA CORPORATION.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Usage:
#   conda build -c defaults -c conda-forge .
package:
  name: dask_cuml
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.0.dev').lstrip('v') }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
  run:
    - python
    - cudf
    - dask >=0.19.0
    - distributed >=1.23.0
    - pandas 0.20.3
		- cuml
		- dask_cudf
test:
  imports:
    - dask_cudf

about:
  home: http://rapids.ai
  license: Apache
  # license_file: LICENSE
  summary: A Partitioned GPU Dataframe